Happy Number
codedecks-in/LeetCode-Solutions pull request #51
Opened 2020-10-02 05:57 UTC by ifenil

# Pull Request Template

## Description

A happy number is a number Starting with any positive integer, replace the number by the sum of the squares of its digits, and repeat the process until the number equals 1 if we get 1 so that number is Happy else not Happy.

## Put check marks:
## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
- [ x ] Added problem & solution under correct topic.
- [ x ] Specified Space & Time complexity.
- [ x ] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Make sure all below guidelines are followed else PR will get Reject:

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ ] I have commented my code so that it is easy to understand
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] Any dependent changes have been merged and published in downstream modules

2020-10-02 12:21 UTC, lokendra1704 requested changes
In Happy-Number.java, The use of HashSet can be avoided. Can you improve your solution?

2020-10-02 12:55 UTC, ifenil commented
can i use list inplace set?

2020-10-02 14:18 UTC, ifenil commented
i made changes, now can you merge it

2020-10-02 18:28 UTC, lokendra1704 submitted a review, later dismissed

2020-10-02 18:34 UTC, ifenil commented
I just made changes in readme file

2020-10-02 18:36 UTC, lokendra1704 requested changes
You repeated few names. Can you fix it?

2020-10-02 18:37 UTC, ifenil commented
Ok I check it

2020-10-02 18:37 UTC, lokendra1704 commented
> i made changes, now can you merge it

I like the new Solution 👌

2020-10-02 18:39 UTC, lokendra1704 requested changes

2020-10-02 18:39 UTC, lokendra1704 commented on README.md
> +| [Ishika Goel](https://github.com/ishikagoel5628)  <br>  <img src="https://github.com/Nour-Grati.png" width="100" height="100">                   | India   | C++                  | [Leetcode](https:
See this is repeated

2020-10-02 18:39 UTC, lokendra1704 commented on README.md
> +| [Prashansa Tanwar](https://github.com/prashansatanwar)  <br>  <img src="https://github.com/prashansatanwar.png" width="100" height="100">        | India   | C++                  | [Leetcode](https:
And this too

2020-10-02 18:39 UTC, lokendra1704 commented on README.md
> +| [Avinash Trivedi](https://github.com/trivediavinash)  <br>   <img src="https://github.com/trivediavinash.png" width="100" height="100">          | India   | C++                  | [Leetcode](https:
and this one too

2020-10-02 18:42 UTC, lokendra1704 submitted a review, later dismissed

2020-10-02 18:45 UTC, ifenil commented
Ok I do it

2020-10-02 18:50 UTC, ifenil commented
now it's solved can you pls check it

2020-10-02 19:09 UTC, lokendra1704 approved these changes

2020-10-03 09:25 UTC, ifenil commented
Why it's not merge yet?

2020-10-03 12:30 UTC, lokendra1704 commented
> Why it's not merge yet?

Only @GouravRusiya30 can merge the requests. He might be busy. Don't worry, It will get merged soon.

2020-10-03 13:46 UTC, merged